import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Cinematic Intelligence Design System — exact tokens from DESIGN.md
        "secondary-fixed": "#abefe8",
        "on-primary-fixed": "#002113",
        "inverse-primary": "#006c49",
        "on-primary": "#003824",
        "surface-variant": "#2e3447",
        "on-secondary-fixed": "#00201e",
        "error-container": "#93000a",
        "surface-container-low": "#151b2d",
        "surface-tint": "#4edea3",
        surface: "#0c1324",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "surface-container-lowest": "#070d1f",
        "outline-variant": "#3c4a42",
        "on-tertiary-container": "#550093",
        "on-primary-container": "#00422b",
        "secondary-container": "#005550",
        primary: "#4edea3",
        "on-surface": "#dce1fb",
        "primary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#2c0051",
        "primary-fixed": "#6ffbbe",
        "inverse-on-surface": "#2a3043",
        "on-secondary": "#003734",
        "inverse-surface": "#dce1fb",
        "primary-container": "#10b981",
        "surface-dim": "#0c1324",
        "on-secondary-fixed-variant": "#00504b",
        "on-secondary-container": "#84c8c1",
        "surface-container-high": "#23293c",
        "surface-bright": "#33394c",
        background: "#0c1324",
        "surface-container-highest": "#2e3447",
        error: "#ffb4ab",
        "on-primary-fixed-variant": "#005236",
        "secondary-fixed-dim": "#8fd3cc",
        "surface-container": "#191f31",
        "on-tertiary": "#490080",
        "on-surface-variant": "#bbcabf",
        outline: "#86948a",
        "tertiary-fixed-dim": "#ddb7ff",
        "on-background": "#dce1fb",
        secondary: "#8fd3cc",
        tertiary: "#ddb7ff",
        "tertiary-container": "#c487ff",
        "on-tertiary-fixed-variant": "#6900b3",
        "tertiary-fixed": "#f0dbff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1.5rem",
        base: "4px",
        xs: "0.25rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "1.5rem",
        xl: "2.5rem",
        "2xl": "4rem",
        "margin-mobile": "1rem",
        "margin-desktop": "2rem",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "data-mono": ["14px", { lineHeight: "1.4", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "pulse-critical": "pulse-red 2s infinite",
        "float": "float 6s ease-in-out infinite",
        "glow": "glow 2s ease-in-out infinite alternate",
        "slide-up": "slideUp 0.4s ease-out",
        "fade-in": "fadeIn 0.3s ease-out",
        "spin-slow": "spin 8s linear infinite",
      },
      keyframes: {
        "pulse-red": {
          "0%": { boxShadow: "0 0 0 0 rgba(255, 180, 171, 0.4)" },
          "70%": { boxShadow: "0 0 0 10px rgba(255, 180, 171, 0)" },
          "100%": { boxShadow: "0 0 0 0 rgba(255, 180, 171, 0)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
        glow: {
          from: { boxShadow: "0 0 20px rgba(78, 222, 163, 0.2)" },
          to: { boxShadow: "0 0 40px rgba(78, 222, 163, 0.5)" },
        },
        slideUp: {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
      },
      backgroundImage: {
        mesh: `radial-gradient(at 0% 0%, rgba(16, 185, 129, 0.15) 0px, transparent 50%),
               radial-gradient(at 100% 100%, rgba(105, 0, 179, 0.15) 0px, transparent 50%)`,
        "emerald-gradient": "linear-gradient(180deg, #10b981 0%, #006c49 100%)",
      },
      maxWidth: {
        "screen-2xl": "1600px",
      },
      boxShadow: {
        emerald: "0 0 15px rgba(78, 222, 163, 0.3)",
        "emerald-lg": "0 0 40px rgba(78, 222, 163, 0.3)",
        purple: "0 0 40px -10px rgba(196, 135, 255, 0.3)",
        "purple-lg": "0 8px 32px rgba(196, 135, 255, 0.15)",
        critical: "0 0 15px rgba(255, 180, 171, 0.4)",
        nav: "0 -8px 32px rgba(0, 0, 0, 0.3)",
        card: "0 8px 32px rgba(0, 0, 0, 0.2)",
      },
    },
  },
  plugins: [],
};

export default config;
